---
title: Trying GCTA to perform heritability analysis
author: Martha Aquino
date: '2018-09-03'
slug: trying-gcta-to-perform-heritability-analysis
categories:
  - Coding
  - Experiments
tags:
  - GCTA
  - Genomic Data
  - Heritability
  - Linux
---

#Introduction
Although heritability estimates have been obtained from gaston, I was unable to obtain signficance values for the estimates. This is important as it will help me prioritise the phenotypes and principal components that will be carried forward to the pedigree-based GWAS. Therefore, I will attempt to re-calculate the heritability estimates using GCTA (http://cnsgenomics.com/software/gcta/#Overview). GCTA is a command line program that uses PLINK input and output. 

#Methods and Results 

###1. Download Linux version of GCTA and unzip in /Data folder.

###2 Check that GCTA has been installed properly 
```{bash, eval = FALSE}
./gcta64
```

###3. Make GRM from the NIES genomic data 
```{bash, eval = FALSE}
./gcta64 --bfile merged_nies_geno_210818 --make-grm --out gcta_output/merged_nies_grm
```

###4. Perform PCA on genomic data, including 2 PCs 
```{bash, eval = FALSE}
./gcta64 --bfile merged_nies_geno_210818 --make-grm --pca 2 --out gcta_output/merged_nies_pca
```

From the PCA performed in gaston, only 2 principal components are required to correct for population stratification in this data set. 

###5. Try estimating heritability for one trait to see what the output is and if the estimate matches gaston results. 

Ideally, the GCTA estimates should be very similar as it uses a linear mixed model for estimation as well. The values are not expected to be identical because different packages/softwares perform analyses slightly differently and will result in decimal point differences. 

```{bash, eval = FALSE}
./gcta64 --reml --grm gcta_output/merged_nies_grm --pheno nies_pheno_020918.txt --mpheno 25 --reml-pred-rand -qcovar gcta_output/merged_nies_pca --out gcta_output/est_her_test
```

Note: the above function should allow me to generate the heritability estimates one-by-one. The "mpheno" function takes a PLAIN TEXT FILE with family and individual IDs in the first two columns respectively, and then data for the phenotypic variables in subsequent columns. The mpheno modifier takes a number from which you can specify the column for heritability estimation e.g. '25' will take the data in the 27th column (i.e. 25th phenotype column = R.CDR)

The output of this exercise is as follows: 

Source | Variance | SE
-------|----------|---------
V(G)   | 0.025569 | 0.006542
V(e)   | 0.017285 | 0.004785 
Vp     | 0.042853 | 0.003667 
V(G)/Vp| 0.596660 | 0.122792 
LogL   | 384.161  |          
logL0  | 375.013  |          
LRT    | 18.296   |          
df     | 1        |          
Pval   |9.4535e-06|          

The value relating to V(G)/Vp gives the heritability estimate for the trait (R CDR) and the corresponding p-value suggests that this value is statistically signficant. Interestingly, the estimate obtained for this trait is very similar to the estimate obtained using 'gaston' (in previous entry). 

###6. Repeat exercise for other traits

```{r}
read.csv('C:/Users/Martha/Documents/Honours/Project/honours.project/Data/gcta_output/trait_heritability_comparison.csv')
```

The gaston results were from Miles. The same traits appear to be heritable (p <0.05) and estimates are very similar, some only differing by decimal point values.

The issue with my current method of estimating heritability is that I have to repeat the code for each trait and separate file sets are generated for each trait. I wrote a loop for the function, however, separate files are still generated for each trait. 

```{bash, eval = FALSE}
for i in {1..27}
do 
  ./gcta64 --reml --grm gcta_output/merged_nies_grm --pheno nies_pheno_020918.txt --mpheno $i --reml-pred-rand     --qcovar gcta_output/merged_nies_pca.eigenvec --out gcta_output/$i.est
  
  head gcta_output/$i.est.hsq

done
```

This loop generates the heritability estimates for each trait and generates separate files for each estimate. GCTA does not take a phenotypic file with headers, which is why the files are labelled with numbers instead of the trait. 